version: "3"
services:

  agent:
      image: garugaru/warden
      entrypoint: warden agent
      environment:
        REPORTER: statsd
        STATSD_HOST: ${STATSD_HOST}
      networks:
        - statsd
      volumes:
        - "/proc:/host/proc"
        - "/sys:/host/sys"
        - "/var:/host/var"
        - "/etc:/host/etc"
      deploy:
        mode: global
        restart_policy:
          condition: on-failure
networks:
  statsd:
    external: true