version: "3"
services:

  warden:
      image: garugaru/warden
      build:
        context: ../
        dockerfile: docker/Dockerfile.dev
      volumes:
        - "/proc:/host/proc"
        - "/sys:/host/sys"
        - "/var:/host/var"
        - "/etc:/host/etc"