version: "3"
services:

  warden:
      image: garugaru/warden
      build:
        context: ../
        dockerfile: docker/Dockerfile.dev
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
